package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

// generateAliases parses the generated protobuf file and emits a root-package
// alias for every exported top-level type, const, and var, so that
// pg_query.SelectStmt, pg_query.JoinType_JOIN_INNER, pg_query.Node_AConst,
// etc. all resolve exactly as they do in pg_query_go once the import is
// aliased to pg_query.
func generateAliases(pbPath, outPath string) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, pbPath, nil, 0)
	if err != nil {
		return err
	}

	var types, consts, vars []string
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gd.Specs {
			switch s := spec.(type) {
			case *ast.TypeSpec:
				if s.Name.IsExported() {
					types = append(types, s.Name.Name)
				}
			case *ast.ValueSpec:
				for _, name := range s.Names {
					if !name.IsExported() {
						continue
					}
					switch gd.Tok {
					case token.CONST:
						consts = append(consts, name.Name)
					case token.VAR:
						vars = append(vars, name.Name)
					}
				}
			}
		}
	}
	if len(types) == 0 {
		return fmt.Errorf("no exported types found in %s", pbPath)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/generate. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Aliases every exported identifier of ast/pg_query.pb.go into the root\n")
	b.WriteString("// package for drop-in compatibility with pg_query_go.\n\n")
	b.WriteString("package oliphant\n\n")
	b.WriteString("import \"github.com/sqlc-dev/oliphant/ast\"\n\n")
	for _, n := range types {
		fmt.Fprintf(&b, "type %s = ast.%s\n", n, n)
	}
	b.WriteString("\nconst (\n")
	for _, n := range consts {
		fmt.Fprintf(&b, "\t%s = ast.%s\n", n, n)
	}
	b.WriteString(")\n\nvar (\n")
	for _, n := range vars {
		fmt.Fprintf(&b, "\t%s = ast.%s\n", n, n)
	}
	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt aliases: %w", err)
	}
	return os.WriteFile(outPath, src, 0o644)
}
