package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
)

// PG_KEYWORD("abort", ABORT_P, UNRESERVED_KEYWORD, BARE_LABEL)
var kwRe = regexp.MustCompile(`^PG_KEYWORD\("([a-z_]+)",\s*([A-Za-z_]+),\s*([A-Z_]+),\s*([A-Z_]+)\)`)

// generateKeywords emits the keyword tables from the pinned kwlist.h.
// The four reserved-ness categories and the orthogonal bare-label attribute
// are exactly PostgreSQL's; every identifier-position consumption in the
// parser routes through helpers encoding these sets.
func generateKeywords(kwlistPath, outPath string) error {
	data, err := os.ReadFile(kwlistPath)
	if err != nil {
		return err
	}

	type kw struct {
		name, token, category string
		bareLabel             bool
	}
	var kws []kw
	for _, line := range bytes.Split(data, []byte("\n")) {
		m := kwRe.FindSubmatch(line)
		if m == nil {
			continue
		}
		var cat string
		switch string(m[3]) {
		case "UNRESERVED_KEYWORD":
			cat = "Unreserved"
		case "COL_NAME_KEYWORD":
			cat = "ColName"
		case "TYPE_FUNC_NAME_KEYWORD":
			cat = "TypeFuncName"
		case "RESERVED_KEYWORD":
			cat = "Reserved"
		default:
			return fmt.Errorf("unknown keyword category %q", m[3])
		}
		var bare bool
		switch string(m[4]) {
		case "BARE_LABEL":
			bare = true
		case "AS_LABEL":
			bare = false
		default:
			return fmt.Errorf("unknown label kind %q", m[4])
		}
		kws = append(kws, kw{string(m[1]), string(m[2]), cat, bare})
	}
	if len(kws) == 0 {
		return fmt.Errorf("no PG_KEYWORD entries found in %s", kwlistPath)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/generate from internal/reference/kwlist.h. DO NOT EDIT.\n\n")
	b.WriteString("package lexer\n\n")
	b.WriteString(`// KeywordCategory is PostgreSQL's keyword reserved-ness classification
// (kwlist.h). It maps 1:1 onto the protobuf KeywordKind enum minus NO_KEYWORD.
type KeywordCategory int

const (
	Unreserved   KeywordCategory = iota // unreserved_keyword
	ColName                            // col_name_keyword
	TypeFuncName                       // type_func_name_keyword
	Reserved                           // reserved_keyword
)

// Keyword is one kwlist.h entry. Token is the bison token name from gram.y
// (e.g. "ABORT_P"); BareLabel is the PG 14+ bare_label_keyword attribute
// (SELECT expr alias without AS).
type Keyword struct {
	Name      string
	Token     string
	Category  KeywordCategory
	BareLabel bool
}

`)
	fmt.Fprintf(&b, "// Keywords holds all %d keywords of the pinned grammar, keyed by their\n", len(kws))
	b.WriteString("// lower-case SQL spelling.\n")
	b.WriteString("var Keywords = map[string]Keyword{\n")
	for _, k := range kws {
		fmt.Fprintf(&b, "\t%q: {Name: %q, Token: %q, Category: %s, BareLabel: %v},\n",
			k.name, k.name, k.token, k.category, k.bareLabel)
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt keywords: %w", err)
	}
	if err := os.MkdirAll("internal/lexer", 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, src, 0o644)
}
