package main

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

// generatePlpgsql emits internal/plpgsql/tables.go from the pinned
// pl_reserved_kwlist.h / pl_unreserved_kwlist.h (keyword → token maps, the
// data pl_scanner.c compiles in) and plerrcodes.h (the exception condition
// name table pl_comp.c's exception_label_map includes; only the name and its
// number of entries matter — dump_condition serializes condname alone, and
// duplicate names produce chains of that length).
func generatePlpgsql(refDir, outPath string) error {
	kwRe := regexp.MustCompile(`PG_KEYWORD\("([a-z_]+)",\s*(K_[A-Z_]+)\)`)
	readKeywords := func(file string) ([][2]string, error) {
		src, err := os.ReadFile(refDir + "/" + file)
		if err != nil {
			return nil, err
		}
		var out [][2]string
		for _, m := range kwRe.FindAllStringSubmatch(string(src), -1) {
			out = append(out, [2]string{m[1], m[2]})
		}
		if len(out) == 0 {
			return nil, fmt.Errorf("%s: no PG_KEYWORD entries found", file)
		}
		return out, nil
	}

	reserved, err := readKeywords("pl_reserved_kwlist.h")
	if err != nil {
		return err
	}
	unreserved, err := readKeywords("pl_unreserved_kwlist.h")
	if err != nil {
		return err
	}

	errSrc, err := os.ReadFile(refDir + "/plerrcodes.h")
	if err != nil {
		return err
	}
	condRe := regexp.MustCompile(`"([a-z_]+)",\s*ERRCODE_[A-Z_0-9]+`)
	condCount := map[string]int{}
	var condOrder []string
	for _, m := range condRe.FindAllStringSubmatch(string(errSrc), -1) {
		if condCount[m[1]] == 0 {
			condOrder = append(condOrder, m[1])
		}
		condCount[m[1]]++
	}
	if len(condOrder) == 0 {
		return fmt.Errorf("plerrcodes.h: no condition entries found")
	}
	sort.Strings(condOrder)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/generate -plpgsql from internal/reference/\n")
	b.WriteString("// pl_reserved_kwlist.h, pl_unreserved_kwlist.h, and plerrcodes.h\n")
	b.WriteString("// (libpg_query 18.0.0). DO NOT EDIT.\n\npackage plpgsql\n\n")

	b.WriteString("// reservedKeywords is pl_reserved_kwlist.h: these are passed to the core\n")
	b.WriteString("// scanner's keyword list, so they win over any variable name.\n")
	b.WriteString("var reservedKeywords = map[string]plToken{\n")
	for _, kw := range reserved {
		fmt.Fprintf(&b, "\t%q: %s,\n", kw[0], kw[1])
	}
	b.WriteString("}\n\n")

	b.WriteString("// unreservedKeywords is pl_unreserved_kwlist.h: checked only where the\n")
	b.WriteString("// grammar wants a keyword and no variable matched.\n")
	b.WriteString("var unreservedKeywords = map[string]plToken{\n")
	for _, kw := range unreserved {
		fmt.Fprintf(&b, "\t%q: %s,\n", kw[0], kw[1])
	}
	b.WriteString("}\n\n")

	b.WriteString("// errConditions maps exception condition names to their number of\n")
	b.WriteString("// entries in exception_label_map (plpgsql_parse_err_condition returns a\n")
	b.WriteString("// chain with one node per entry).\n")
	b.WriteString("var errConditions = map[string]int{\n")
	for _, name := range condOrder {
		fmt.Fprintf(&b, "\t%q: %d,\n", name, condCount[name])
	}
	b.WriteString("}\n\n")

	types, err := readBuiltinTypes(refDir)
	if err != nil {
		return err
	}
	b.WriteString("// builtinTypes is pg_query_pg_type.c: the inline pg_type data the\n")
	b.WriteString("// SearchSysCache1/GetSysCacheOid mocks serve, in table order.\n")
	b.WriteString("var builtinTypes = []builtinType{\n")
	for _, t := range types {
		fmt.Fprintf(&b, "\t{oid: %s, name: %q, typtype: '%s', typcollation: %s, typarray: %s},\n",
			t[0], t[1], t[2], t[3], t[4])
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt plpgsql tables: %w", err)
	}
	return os.WriteFile(outPath, src, 0o644)
}

// readBuiltinTypes parses pg_query_pg_type.c's table, resolving the OID and
// collation macros against pg_type_d.h (plus the two well-known collation
// OIDs from pg_collation_d.h).
func readBuiltinTypes(refDir string) ([][5]string, error) {
	defSrc, err := os.ReadFile(refDir + "/pg_type_d.h")
	if err != nil {
		return nil, err
	}
	oids := map[string]string{
		"InvalidOid":            "0",
		"C_COLLATION_OID":       "950",
		"DEFAULT_COLLATION_OID": "100",
	}
	defRe := regexp.MustCompile(`(?m)^#define ([A-Z_0-9]+OID) (\d+)`)
	for _, m := range defRe.FindAllStringSubmatch(string(defSrc), -1) {
		oids[m[1]] = m[2]
	}
	typtypes := map[string]string{}
	ttRe := regexp.MustCompile(`(?m)^#define\s+(TYPTYPE_[A-Z]+)\s+'(.)'`)
	for _, m := range ttRe.FindAllStringSubmatch(string(defSrc), -1) {
		typtypes[m[1]] = m[2]
	}

	src, err := os.ReadFile(refDir + "/pg_query_pg_type.c")
	if err != nil {
		return nil, err
	}
	rowRe := regexp.MustCompile(`\{ ([A-Za-z_0-9]+), "([^"]+)", [^,]+, [^,]+, (TYPTYPE_[A-Z]+), [^,]+, [^,]+, ([A-Za-z_0-9]+), ([A-Za-z_0-9]+) \}`)
	var out [][5]string
	for _, m := range rowRe.FindAllStringSubmatch(string(src), -1) {
		resolve := func(tok string) (string, error) {
			if v, ok := oids[tok]; ok {
				return v, nil
			}
			if _, err := fmt.Sscanf(tok, "%d", new(int)); err == nil {
				return tok, nil
			}
			return "", fmt.Errorf("pg_query_pg_type.c: unresolved oid macro %q", tok)
		}
		oid, err := resolve(m[1])
		if err != nil {
			return nil, err
		}
		arr, err := resolve(m[4])
		if err != nil {
			return nil, err
		}
		coll, err := resolve(m[5])
		if err != nil {
			return nil, err
		}
		tt, ok := typtypes[m[3]]
		if !ok {
			return nil, fmt.Errorf("pg_query_pg_type.c: unknown typtype %q", m[3])
		}
		out = append(out, [5]string{oid, m[2], tt, coll, arr})
	}
	if len(out) < 100 {
		return nil, fmt.Errorf("pg_query_pg_type.c: only %d rows parsed", len(out))
	}
	return out, nil
}
