package main

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

// generatePlpgsql emits internal/plpgsql/tables.go from the pinned
// pl_reserved_kwlist.h / pl_unreserved_kwlist.h (keyword → token maps, the
// data pl_scanner.c compiles in) and plerrcodes.h (the exception condition
// name table pl_comp.c's exception_label_map includes; only the name and its
// number of entries matter — dump_condition serializes condname alone, and
// duplicate names produce chains of that length).
func generatePlpgsql(refDir, outPath string) error {
	kwRe := regexp.MustCompile(`PG_KEYWORD\("([a-z_]+)",\s*(K_[A-Z_]+)\)`)
	readKeywords := func(file string) ([][2]string, error) {
		src, err := os.ReadFile(refDir + "/" + file)
		if err != nil {
			return nil, err
		}
		var out [][2]string
		for _, m := range kwRe.FindAllStringSubmatch(string(src), -1) {
			out = append(out, [2]string{m[1], m[2]})
		}
		if len(out) == 0 {
			return nil, fmt.Errorf("%s: no PG_KEYWORD entries found", file)
		}
		return out, nil
	}

	reserved, err := readKeywords("pl_reserved_kwlist.h")
	if err != nil {
		return err
	}
	unreserved, err := readKeywords("pl_unreserved_kwlist.h")
	if err != nil {
		return err
	}

	errSrc, err := os.ReadFile(refDir + "/plerrcodes.h")
	if err != nil {
		return err
	}
	condRe := regexp.MustCompile(`"([a-z_]+)",\s*ERRCODE_[A-Z_0-9]+`)
	condCount := map[string]int{}
	var condOrder []string
	for _, m := range condRe.FindAllStringSubmatch(string(errSrc), -1) {
		if condCount[m[1]] == 0 {
			condOrder = append(condOrder, m[1])
		}
		condCount[m[1]]++
	}
	if len(condOrder) == 0 {
		return fmt.Errorf("plerrcodes.h: no condition entries found")
	}
	sort.Strings(condOrder)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/generate -plpgsql from internal/reference/\n")
	b.WriteString("// pl_reserved_kwlist.h, pl_unreserved_kwlist.h, and plerrcodes.h\n")
	b.WriteString("// (libpg_query 17-6.2.2). DO NOT EDIT.\n\npackage plpgsql\n\n")

	b.WriteString("// reservedKeywords is pl_reserved_kwlist.h: these are passed to the core\n")
	b.WriteString("// scanner's keyword list, so they win over any variable name.\n")
	b.WriteString("var reservedKeywords = map[string]plToken{\n")
	for _, kw := range reserved {
		fmt.Fprintf(&b, "\t%q: %s,\n", kw[0], kw[1])
	}
	b.WriteString("}\n\n")

	b.WriteString("// unreservedKeywords is pl_unreserved_kwlist.h: checked only where the\n")
	b.WriteString("// grammar wants a keyword and no variable matched.\n")
	b.WriteString("var unreservedKeywords = map[string]plToken{\n")
	for _, kw := range unreserved {
		fmt.Fprintf(&b, "\t%q: %s,\n", kw[0], kw[1])
	}
	b.WriteString("}\n\n")

	b.WriteString("// errConditions maps exception condition names to their number of\n")
	b.WriteString("// entries in exception_label_map (plpgsql_parse_err_condition returns a\n")
	b.WriteString("// chain with one node per entry).\n")
	b.WriteString("var errConditions = map[string]int{\n")
	for _, name := range condOrder {
		fmt.Fprintf(&b, "\t%q: %d,\n", name, condCount[name])
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt plpgsql tables: %w", err)
	}
	return os.WriteFile(outPath, src, 0o644)
}
